In [2]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_csv("LaLiga2023-24/standard_player_stat.csv")

In [6]:
data.head()

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,Ast.1,G+A.1,G-PK.1,G+A-PK,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1,Matches
0,Nabil Aberdin,fr FRA,DF,Getafe,20.0,2002.0,2.0,2.0,180,2.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches
1,Abner,br BRA,DF,Betis,23.0,2000.0,23.0,15.0,"1,400",15.6,...,0.06,0.06,0.00,0.06,0.01,0.06,0.07,0.01,0.07,Matches
2,Abdel Abqar,ma MAR,DF,Alavés,24.0,1999.0,27.0,27.0,"2,312",25.7,...,0.00,0.00,0.00,0.00,0.02,0.01,0.02,0.02,0.02,Matches
3,Marcos Acuña,ar ARG,DF,Sevilla,31.0,1991.0,21.0,18.0,"1,292",14.4,...,0.14,0.21,0.07,0.21,0.02,0.11,0.13,0.02,0.13,Matches
4,Julen Agirrezabala,es ESP,GK,Athletic Club,22.0,2000.0,4.0,2.0,238,2.6,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches

In [8]:
data.duplicated().sum()

23

In [14]:
print(data.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
628    False
629    False
630    False
631    False
632    False
Length: 633, dtype: bool

In [18]:
data.isna().sum()

Player        24
Nation        24
Pos           24
Squad         24
Age           25
Born          25
MP            24
Starts        24
Min           24
90s           24
Gls           24
Ast           24
G+A           24
G-PK          24
PK            24
PKatt         24
CrdY          24
CrdR          24
xG            24
npxG          24
xAG           24
npxG+xAG      24
PrgC          24
PrgP          24
PrgR          24
Gls.1         24
Ast.1         24
G+A.1         24
G-PK.1        24
G+A-PK        24
xG.1          24
xAG.1         24
xG+xAG        24
npxG.1        24
npxG+xAG.1    24
Matches       24
dtype: int64

In [30]:
data=data.dropna()

In [32]:
data.duplicated().sum()

0

In [34]:
data["Player"].nunique()

596

In [48]:
data[data["Player"].duplicated(keep="last")]

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,Ast.1,G+A.1,G-PK.1,G+A-PK,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1,Matches
42,Ezequiel Ávila,ar ARG,"FW,MF",Osasuna,29.0,1994.0,17.0,10.0,864,9.6,...,0.31,0.42,0.10,0.42,0.21,0.24,0.45,0.21,0.45,Matches
162,Abde Ezzalzouli,ma MAR,"FW,MF",Barcelona,21.0,2001.0,2.0,0.0,68,0.8,...,0.00,0.00,0.00,0.00,0.28,0.09,0.37,0.28,0.37,Matches
177,Fernando,es ESP,GK,Almería,33.0,1990.0,4.0,4.0,360,4.0,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches
189,Javi Galán,es ESP,DF,Atlético Madrid,28.0,1994.0,5.0,0.0,88,1.0,...,0.00,0.00,0.00,0.00,0.00,0.06,0.06,0.00,0.06,Matches
196,Eric García,es ESP,DF,Barcelona,22.0,2001.0,2.0,0.0,57,0.6,...,0.00,0.00,0.00,0.00,0.07,0.00,0.07,0.07,0.07,Matches
318,Anthony Lozano,hn HON,"MF,FW",Getafe,30.0,1993.0,6.0,0.0,92,1.0,...,0.00,0.00,0.00,0.00,0.18,0.25,0.43,0.18,0.43,Matches
422,Samu Omorodion,es ESP,FW,Alavés,19.0,2004.0,34.0,21.0,"1,918",21.3,...,0.05,0.42,0.38,0.42,0.51,0.06,0.56,0.51,0.56,Matches
440,Gabriel Paulista,br BRA,DF,Atlético Madrid,32.0,1990.0,5.0,5.0,405,4.5,...,0.00,0.00,0.00,0.00,0.04,0.02,0.06,0.04,0.06,Matches
462,Portu,es ESP,FW,Getafe,31.0,1992.0,3.0,0.0,97,1.1,...,0.00,0.00,0.00,0.00,0.15,0.14,0.29,0.15,0.29,Matches
547,Alex Sola,es ESP,"FW,MF",Alavés,24.0,1999.0,29.0,14.0,"1,262",14.0,...,0.21,0.21,0.00,0.21,0.12,0.16,0.28,0.12,0.28,Matches
608,Nacho Vidal,es ESP,"DF,FW",Osasuna,28.0,1995.0,7.0,0.0,96,1.1,...,0.00,0.94,0.94,0.94,0.28,0.01,0.29,0.28,0.29,Matches
611,Jonathan Viera,es ESP,"MF,FW",Las Palmas,33.0,1989.0,9.0,7.0,617,6.9,...,0.15,0.44,0.00,0.15,0.33,0.14,0.47,0.10,0.24,Matches